services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  auction-service:
    image: 7devio/auction-service:latest
    build:
        context: .
        dockerfile: server/AuctionService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres;Database=auctions
      - IdentityServiceUrl=http://identity-service
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq
  search-service:
    image: 7devio/search-service:latest
    build:
      context: .
      dockerfile: server/SearchService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:root@mongodb
      - AuctionServiceUrl=http://auction-service
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
  identity-service:
    image: 7devio/identity-service:latest
    build:
      context: .
      dockerfile: server/IdentityService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres;Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  gateway-service:
    image: 7devio/gateway-service:latest
    build:
      context: .
      dockerfile: server/GatewayService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
volumes:
    pgdata:
    mongodata: