networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      custom:
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    networks:
      custom:
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      custom:
  auction-service:
    image: 7devio/auction-service:latest
    build:
      context: .
      dockerfile: server/AuctionService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres;Database=auctions
      - IdentityServiceUrl=http://identity-service
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 7001:80
      - 7777:7777
    networks:
      custom:
    depends_on:
      - postgres
      - rabbitmq
  search-service:
    image: 7devio/search-service:latest
    build:
      context: .
      dockerfile: server/SearchService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:root@mongodb
      - AuctionServiceUrl=http://auction-service
    ports:
      - 7002:80
    networks:
      custom:
    depends_on:
      - mongodb
      - rabbitmq
  identity-service:
    image: 7devio/identity-service:latest
    build:
      context: .
      dockerfile: server/IdentityService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=http://app.shiftswap.com
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres;Database=identity
      - VIRTUAL_HOST=id.shiftswap.com
    networks:
      custom:
        ipv4_address: 10.5.0.200
    depends_on:
      - postgres
  gateway-service:
    image: 7devio/gateway-service:latest
    build:
      context: .
      dockerfile: server/GatewayService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - VIRTUAL_HOST=api.shiftswap.com
      - ClientApp=http://app.shiftswap.com
    networks:
      custom:
  bidding-service:
    image: 7devio/bidding-service:latest
    build:
      context: .
      dockerfile: server/BiddingService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:root@mongodb
      - IdentityServiceUrl=http://identity-service
      - GrpcAuction=http://auction-service:7777
    ports:
      - 7003:80
    networks:
      custom:
    depends_on:
      - mongodb
      - rabbitmq
  notifications-service:
    image: 7devio/notifications-service:latest
    build:
      context: .
      dockerfile: server/NotificationsService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:80
    networks:
      custom:
    depends_on:
      - rabbitmq
  web-app:
    image: 7devio/web-app:latest
    build:
      context: .
      dockerfile: client/shift-swapper-web-app/DockerFile
    volumes:
      - /var/lib/web/data
    networks:
      custom:
    extra_hosts:
      - id.shiftswap.com:10.5.0.200
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - NEXTAUTH_SECRET=somethingreallyreallysecret
      - NEXTAUTH_URL=http://app.shiftswap.com
      - NEXTAUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-service/
      - ID_URL=http://id.shiftswap.com
      - NEXT_PUBLIC_NOTIFY_URL=http://gateway-service/notifications
      - VIRTUAL_HOST=app.shiftswap.com
      - VIRTUAL_PORT=3000
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    networks:
        custom:
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./devcerts:/etc/nginx/certs
volumes:
  pgdata:
  mongodata: