FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY ./package*.json ./
RUN npm install

FROM node:20-alpine AS dev-runner
WORKDIR /app

ENV NODE_ENV development

# Copy all files for development
COPY --from=deps /app/node_modules ./node_modules
COPY ./ ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
