FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY client/shift-swapper-web-app/package*.json ./
RUN npm install

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY client/shift-swapper-web-app ./

ENV NEXT_TELEMETRY_DISABLED 1

# Development mode, run the Next.js development server
CMD ["npm", "run", "dev"]


#Also change docker-compose to - NODE_ENV=development