FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY client/shift-swapper-web-app/package*.json ./
RUN npm install

FROM node:20-alpine AS dev-runner
WORKDIR /app

ENV NODE_ENV development

# Copy all files for development
COPY --from=deps /app/node_modules ./node_modules
COPY client/shift-swapper-web-app/ ./

COPY --from=builder /app/next.config.mjs ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/theme.ts ./theme.ts
COPY --from=builder /app/postcss.config.cjs ./postcss.config.cjs

EXPOSE 3000

CMD ["npm", "run", "dev"]
